config/routes.rb
SampleApp::Application.routes.draw do
  
  root to: 'static_pages#home'
  resources :users do
    member do
      get :following, :followers, :photos, :upload_photo
    end
    get :autocomplete_user_name, on: :collection
  end  
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :photos, only: [:create, :destroy]
  resources :password_resets

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by_email(params[:email])
    if user
      user.send_password_reset
      redirect_to root_path, :notice => "Email sent with password reset instructions."
    else
      redirect_to root_path, :error => "Email not sent. Please try again later"
    end
  end
  
  def edit
    @user = User.find_by_password_reset_token!(params[:id])
  end
  
  def update
    @user = User.find_by_password_reset_token!(params[:id])
    if @user.password_reset_sent_at < 2.hours.ago
      redirect_to new_password_reset_path, :alert => "Password &crarr; 
	reset has expired."
    elsif @user.update_attributes(params[:user])
      redirect_to root_path , :notice => "Password has been reset."
    else
      render :edit
    end
  end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<h1>Reset Password</h1>
<div class="row">
<div class="span6 offset3">
<%= form_for @user, :url => password_reset_path(params[:id]) do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    <%= f.submit "Update Password", class: "btn btn-large btn-primary" %>
<% end %>
</div>
</div>

app/views/password_resets/new.html.erb
<h1>Reset Password</h1>

<%= form_tag password_resets_path, :method => :post do %>
  <div class="row">
    <div class="field span6 offset3">
      <%= label_tag :email %>
      <%= text_field_tag :email, params[:email] %>
      <%= submit_tag "Reset Password", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>
    